name: check_win
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check windows-x86_64-devel
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: sh ci/docker_ci.sh ci/check_rhub.R "windows-x86_64-devel"
